version: "3.7"
services:
  frontend:
    image: node:10.15.1
    command: npm run docker
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
  server:
    image: node:10.15.1
    command: npm run docker
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:11.7-alpine
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: secret_server
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: pwd
